apiVersion: v1
kind: Service
metadata:
  name: machine-xperience-frontend-service
spec:
  selector:
    app: machine-xperience-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100