kind: Deployment
apiVersion: apps/v1
metadata:
  name: machine-xperience-frontend-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-xperience-frontend
  template:
    metadata:
      labels:
        app: machine-xperience-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: machine-xperience-frontend-frontend
        image: ghcr.io/patricia-fernandez/machine-xperience-frontend
        ports:
          - containerPort: 80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"